server:
  port: 8081
  servlet:
    context-path: /auth


spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
        show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: 1ghantaA!
#    initialize: true
#    schema=classpath:/schema.sql
#    continue-on-error=true
