#name: Build and Publish Docker Image
#
#on:
#  push:
#    branches: [ "dev" ]
#
#env:
#  IMAGE_NAME: ghcr.io/createandlearn/auth-service/auth
#  DOCKER_BUILDKIT: 1
#
#jobs:
#  build-and-push:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Check if docker/setup-docker is available
#      run: |
#        curl -s https://api.github.com/repos/docker/setup-docker/actions/workflows/main.yml \
#        | grep "docker/setup-docker@" -o \
#        | head -1 \
#        | sed "s/^/docker/setup-docker@/" \
#        | xargs -I {} echo "Using {}"
#    - name: Set up Docker CLI
#      uses: docker/setup-docker@v1
#    - name: Build and push Docker image
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        push: true
#        tags: ghcr.io/<your-username>/<your-repo-name>/<your-image-name>:latest
#
#  build-and-publish:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v2
#    - name: Set up JDK 11
#      uses: actions/setup-java@v2
#      with:
#        java-version: 11
#    - name: Build with Maven
#      run: mvn -B package --file pom.xml
#    - name: Build and push Docker image
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        push: true
#        tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
#    - name: Set up Docker CLI
#      uses: docker/setup-docker@v1
#    - name: Login to GitHub Container Registry
#      uses: docker/login-action@v1
#      with:
#        registry: ghcr.io
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}
#    - name: Push Docker image to GitHub Container Registry
#      run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}